#region Local Var
	Hash hLocal_0 = 0;
	Hash hLocal_1 = 0;
#endregion

void main() // Position - 0x0 Hash - 0xE08F5402 ^0xFFFC35DA
{
	Hash hash;
	int eventData;

	hLocal_0 = 674038080;
	hLocal_1 = DATABINDING::_DATABINDING_ADD_UI_ITEM_LIST_FROM_PATH("", "VirtualizationUnitTestData");
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item0");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 0");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item1");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 1");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item2");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 2");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item3");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 3");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item4");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 4");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item5");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 5");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item6");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 6");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item7");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 7");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item8");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 8");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item9");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 9");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item10");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 10");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item11");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 11");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);
	hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "item12");
	DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item 12");
	DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, -1, "checkbox", hash);

	if (PLAYER::HAS_FORCE_CLEANUP_OCCURRED(4))
		func_1();

	while (true)
	{
		while (UIEVENTS::EVENTS_UI_IS_PENDING(hLocal_0))
		{
			if (UIEVENTS::EVENTS_UI_PEEK_MESSAGE(hLocal_0, &eventData))
			{
				switch (eventData)
				{
					case -1203660660:
						hash = DATABINDING::_DATABINDING_ADD_DATA_CONTAINER(hLocal_1, "itemAA");
						DATABINDING::_DATABINDING_ADD_DATA_STRING(hash, "title", "I am item AA");
						DATABINDING::_DATABINDING_INSERT_UI_ITEM_TO_LIST_FROM_CONTEXT_STRING_ALIAS(hLocal_1, 13, "checkbox", hash);
						break;
				}
			
				UIEVENTS::EVENTS_UI_POP_MESSAGE(hLocal_0);
			}
		}
	
		BUILTIN::WAIT(0);
	}

	return;
}

void func_1() // Position - 0x25B Hash - 0xEC4D310C ^0xBD6C1A3D
{
	DATABINDING::_DATABINDING_REMOVE_DATA_ENTRY(hLocal_1);
	SCRIPTS::TERMINATE_THIS_THREAD();
	return;
}

